'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, variables?: Record<string, string | number>) => string
  formatDate: (date: Date | string, format?: 'short' | 'long' | 'relative') => string
  formatNumber: (num: number) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.scanner': 'Scanner',
    'nav.myLoans': 'Loans Panel',
    'nav.consumables': 'Materials',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.hello': 'Hello',
    'dashboard.notifications': 'Notifications',
    'dashboard.userMenu': 'User menu',
    'dashboard.profile': 'Profile',
    'dashboard.scanToLoan': 'Scan to Loan',
    'dashboard.scanToReturn': 'Scan to Return',
    'dashboard.requestSupplies': 'Request Materials',
    'dashboard.myLoans': 'Loans Panel',
    'dashboard.activeLoans': 'Active Loans',
    'dashboard.recentLoans': 'Recent Loans',
    'dashboard.welcome': 'Scan QR codes to loan or return tools',
    'dashboard.noActiveLoans': 'No Active Loans',
    'dashboard.noActiveLoansDesc': 'You don\'t have any tools currently on loan.',

    // Navigation
    'navigation.home': 'Home',
    'navigation.scanner': 'Scanner',
    'navigation.loans': 'Loans',
    'navigation.consumables': 'Materials',
    'navigation.profile': 'Profile',

    // Scanner
    'scanner.title': 'Scanner',
    'scanner.scanSupplies': 'Request Materials',
    'scanner.scanSuppliesDesc': 'Scan material QR codes to record usage',
    'scanner.scanTools': 'Scan Tools',
    'scanner.scanToolsDesc': 'Scan tool QR codes to loan or return',
    'scanner.manualEntry': 'Manual Entry',
    'scanner.manualEntryDesc': 'Enter QR code manually',
    'scanner.scanning': 'Scanning...',
    'scanner.cancel': 'Cancel Scanning',
    'scanner.processing': 'Processing...',
    'scanner.returnConsumables': 'Return Materials',
    'scanner.returnConsumablesDesc': 'Return unused materials from your practices',

    // Returns
    'returns.title': 'Return Materials',
    'returns.selectDate': 'Select Consumption Date',
    'returns.noConsumptions': 'No consumptions on this date',
    'returns.addToCart': 'Add to Cart',
    'returns.confirmReturn': 'Confirm Return',
    'returns.returnSuccess': 'Return processed successfully',
    'returns.maxReturnable': 'Max returnable',
    'returns.consumed': 'Consumed',
    'returns.returned': 'Returned',
    'returns.returnable': 'Available to return',
    'returns.howItWorks': 'How does it work?',
    'returns.step1': 'Select the date you consumed the items',
    'returns.step2': 'Choose the items you want to return and quantities',
    'returns.step3': 'Add them to the return cart',
    'returns.step4': 'Confirm the return to update stock',
    'returns.selectDatePrompt': 'Select a date',
    'returns.selectDateDesc': 'Choose a consumption date to see items you can return',
    'returns.itemsConsumed': 'Items Consumed',
    'returns.loadingItems': 'Loading items...',
    'returns.returnCart': 'Return Cart',
    'returns.totalToReturn': 'Total to return:',
    'returns.emptyCart': 'Empty Cart',
    'returns.confirmReturnBtn': 'Confirm Return',
    'returns.processing': 'Processing...',
    'returns.noItemsInCart': 'No items in return cart',
    'returns.alreadyReturned': 'You have already returned everything consumed',
    'returns.noRecentConsumptions': 'No recent consumptions',
    'returns.noConsumptionsDesc': 'You have no consumptions in the last 30 days to return.',
    'returns.loadingHistory': 'Loading history...',
    'returns.refresh': 'Refresh',
    'returns.consumptionDate': 'Consumption date:',
    'returns.items': 'Items:',
    'returns.totalConsumed': 'Consumed:',
    'returns.totalReturnable': 'Returnable:',
    'returns.units': 'units',

    // My Loans
    'myLoans.title': 'Loans Panel',
    'myLoans.myLoans': 'My Loans',
    'myLoans.allActiveLoans': 'All Active Loans',
    'myLoans.availableTools': 'Available Tools',
    'myLoans.scanToReturn': 'Scan to Return',
    'myLoans.active': 'Active',
    'myLoans.overdue': 'Overdue',
    'myLoans.returned': 'Returned',
    'myLoans.total': 'Total',
    'myLoans.activeLoans': 'Active Loans',
    'myLoans.history': 'History',
    'myLoans.consumables': 'Materials',
    'myLoans.noActiveLoans': 'No Active Loans',
    'myLoans.noActiveLoansDes': 'You don\'t have any tools currently on loan.',
    'myLoans.noActiveLoansDesc': 'There are no active loans in the system',
    'myLoans.scanToLoanTool': 'Scan to Loan Tool',
    'myLoans.noHistory': 'No Loan History',
    'myLoans.noHistoryDesc': 'Your loan history will appear here.',
    'myLoans.noConsumables': 'No Materials History',
    'myLoans.noConsumablesDesc': 'You haven\'t requested any materials yet.',
    'myLoans.scanToConsume': 'Request Materials',
    'myLoans.backToDashboard': 'Back to Dashboard',
    'myLoans.returning': 'Returning...',
    'myLoans.return': 'Return',
    'myLoans.scanRequiredTitle': 'Scan Required for Returns',
    'myLoans.scanRequiredDesc': 'To return tools, please use the QR scanner',
    'myLoans.allCategories': 'All',
    'myLoans.totalAvailable': 'Total available tools',
    'myLoans.available': 'available',
    'myLoans.noAvailableTools': 'No available tools',
    'myLoans.noAvailableToolsDesc': 'All tools are currently on loan',

    // Consumables
    'consumables.title': 'Materials',
    'consumables.scanQR': 'Scan QR',
    'consumables.management': 'Materials Management',
    'consumables.addItemType': 'Add Material Type',
    'consumables.backToDashboard': 'Back to Dashboard',
    'consumables.totalItems': 'Total Materials',
    'consumables.outOfStock': 'Out of Stock',
    'consumables.lowStock': 'Low Stock',
    'consumables.backorders': 'Backorders',
    'consumables.inventory': 'Inventory',
    'consumables.currentStock': 'Current Stock',
    'consumables.minimumThreshold': 'Minimum Threshold',
    'consumables.quantity': 'Quantity',
    'consumables.quantityToConsume': 'Quantity to Request',
    'consumables.consume': 'Request',
    'consumables.date': 'Date',
    'consumables.notes': 'Notes',
    'consumables.scanAnother': 'Scan Another Material',
    'consumables.inStock': 'In Stock',
    'consumables.cannotConsume': 'This material is out of stock and cannot be requested',

    // Admin Dashboard
    "admin.manageElectronics": "Manage Electronics",
    "admin.totalElectronics": "Electronics Divices",
    'admin.dashboard': 'Admin Dashboard',
    'admin.manageTools': 'Manage Tools',
    'admin.availableTools': 'Available Tools',
    'admin.activeLoans': 'Active Loans',
    'admin.overdueLoans': 'Overdue Loans',
    'admin.totalUsers': 'Total Users',
    'admin.consumableInventory': 'Materials Inventory',
    'admin.lowStockItems': 'Low Stock Materials',
    'admin.systemHealth': 'System Health',
    'admin.good': 'Good',
    'admin.quickActions': 'Quick Actions',
    'admin.addNewTool': 'Add New Tool',
    'admin.addItemType': 'Add Item Type',
    'admin.addUser': 'Add User',
    'admin.generateReport': 'Reports',
    'admin.manageToolsBtn': 'Manage Tools',
    'admin.manageUsers': 'Manage Users',
    'admin.quickAccessDesc': 'Quick access to main system sections',
    'admin.manageToolsDesc': 'View, create and manage',
    'admin.manageUsersDesc': 'View, create and manage',
    'admin.manageMaterialsDesc': 'Stock and restocking',
    'admin.manageElectronicsDesc': 'View, Create and manage',
    'admin.reportsDesc': 'Analysis and statistics',
    'admin.advancedConfig': 'Advanced Configuration',
    'admin.advancedConfigDesc': 'Configuration options and tools for advanced users',
    'admin.manageItemTypes': 'Manage Item Types',
    'admin.manageItemTypesDesc': 'Create/edit types manually',
    'admin.invoiceReports': 'Invoice Reports',
    'admin.invoiceReportsDesc': 'Purchase and invoice reports',
    'admin.auditLogs': 'Audit Logs',
    'admin.auditLogsDesc': 'System change history',
    'admin.systemInfo': 'System Information',
    'admin.databaseStatus': 'Database Status',
    'admin.databaseConnected': 'Connected & Operational',
    'admin.dataRefresh': 'Data Refresh',
    'admin.autoUpdates': 'Auto-updates every minute',
    'admin.realTimeStats': 'Real-Time Stats',
    'admin.liveData': 'Live data from database',
    'admin.lastUpdated': 'Last Updated',

    // My Requests
    'requests.title': 'My Requests',
    'requests.mySupplyRequests': 'My Material Requests',
    'requests.requestSupplies': 'Request Materials',
    'requests.active': 'Active',
    'requests.backorders': 'Backorders',
    'requests.fulfilled': 'Fulfilled',
    'requests.total': 'Total',
    'requests.activeRequests': 'Active Requests',
    'requests.history': 'History',
    'requests.aboutBackorders': 'About Backorders',
    'requests.backordersInfo': 'Items marked as "Pending" are backorders. You\'ll receive a notification when stock becomes available and your request is fulfilled. Requests are processed in the order they were received.',
    'requests.noActiveRequests': 'No Active Requests',
    'requests.noRequestHistory': 'No Request History',
    'requests.noActiveRequestsDesc': 'You don\'t have any active material requests.',
    'requests.requestHistoryDesc': 'Your request history will appear here.',
    'requests.backToDashboard': 'Back to Dashboard',
    'requests.requested': 'Requested',
    'requests.fulfilledQty': 'Fulfilled',
    'requests.remaining': 'Remaining',
    'requests.requestedDate': 'Requested',
    'requests.fulfilledDate': 'Fulfilled',
    'requests.backorderNotice': '⏳ This is a backorder - you\'ll be notified when stock is available',
    'requests.notesLabel': 'Notes',
    'requests.statusFulfilled': 'Fulfilled',
    'requests.statusPartial': 'Partially Fulfilled',
    'requests.statusCancelled': 'Cancelled',
    'requests.statusPending': 'Pending',
    'requests.cancel': 'Cancel',
    'requests.cancelling': 'Cancelling...',
    'requests.loadingRequests': 'Loading requests...',

    // Reports
    'reports.title': 'Generate Report',
    'reports.selectType': 'Select Report Type',
    'reports.dateRange': 'Date Range',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.summary': 'Report Summary',
    'reports.reportType': 'Report Type',
    'reports.period': 'Period',
    'reports.generate': 'Generate Report',
    'reports.generating': 'Generating...',
    'reports.pdfNote': 'The report will be generated in PDF format and can be downloaded or printed.',
    'reports.loansReport': 'Loans Report',
    'reports.loansDesc': 'Overview of all loans, returns, and overdue items',
    'reports.toolsInventory': 'Tools Inventory',
    'reports.toolsDesc': 'Current status and history of all tools',
    'reports.consumablesReport': 'Materials Report',
    'reports.consumablesDesc': 'Stock levels and usage patterns',
    'reports.usersReport': 'Users Report',
    'reports.usersDesc': 'User activity and loan history',
    'reports.auditLog': 'Audit Log',
    'reports.auditDesc': 'System activity and changes log',
    'reports.generatedSuccess': 'generated successfully!',
    'reports.generatedError': 'Failed to generate report',

    // Profile
    'profile.title': 'Profile',
    'profile.language': 'Language',
    'profile.english': 'English',
    'profile.spanish': 'Spanish',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.changePassword': 'Change Password',

    // Change Password
    'changePassword.title': 'Change Password',
    'changePassword.description': 'Update your account password to keep your account secure',
    'changePassword.currentPassword': 'Current Password',
    'changePassword.newPassword': 'New Password',
    'changePassword.confirmPassword': 'Confirm New Password',
    'changePassword.enterCurrentPassword': 'Enter your current password',
    'changePassword.enterNewPassword': 'Enter your new password',
    'changePassword.confirmNewPassword': 'Confirm your new password',
    'changePassword.passwordRequirements': 'Password must be at least 6 characters long',
    'changePassword.changePassword': 'Change Password',
    'changePassword.changing': 'Changing...',
    'changePassword.success': 'Password changed successfully! Redirecting...',
    'changePassword.failed': 'Failed to change password',
    'changePassword.passwordsDoNotMatch': 'Passwords do not match',
    'changePassword.passwordTooShort': 'Password must be at least 6 characters long',
    'changePassword.samePassword': 'New password must be different from current password',
    'changePassword.unknownError': 'An unknown error occurred',

    // Loan Details
    'loan.serial': 'Serial',
    'loan.loaned': 'Loaned',
    'loan.due': 'Due',
    'loan.returned': 'Returned',
    'loan.notes': 'Notes',
    'loan.lost': 'Lost',
    'loan.overdue': 'Overdue',
    'loan.unknownTool': 'Unknown Tool',

    // Consumable Details
    'consumable.consumed': 'Consumed',
    'consumable.at': 'at',
    'consumable.available': 'Available',
    'consumable.units': 'units',
    'consumable.pieces': 'pieces',

    // Notifications
    'notifications.noNotifications': 'No notifications',
    'notifications.markAllAsRead': 'Mark all as read',
    'notifications.justNow': 'Just now',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.allTypes': 'All types',
    'notifications.info': 'Info',
    'notifications.success': 'Success',
    'notifications.warning': 'Warning',
    'notifications.error': 'Error',
    'notifications.noUnread': 'No unread notifications',
    'notifications.delete': 'Delete',
    'notifications.preferences': 'Notification preferences',

    // Common
    'common.loading': 'Loading...',
    'common.loadingLoans': 'Loading loans...',
    'common.loadingInventory': 'Loading inventory...',
    'common.loadingConsumptions': 'Loading consumptions...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.description': 'Description',
    'common.category': 'Category',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.yes': 'Yes',
    'common.close': 'Close',
    'common.no': 'No',

    // ===== CABLE MEASUREMENT CALCULATOR =====
    'calculator.helperText': 'Enter the numbering printed on the cable',
    'calculator.initialLabel': 'Start Number',
    'calculator.finalLabel': 'End Number',
    'calculator.segmentStartLabel': 'Segment Start Number',
    'calculator.segmentEndLabel': 'Segment End Number',
    'calculator.calculated': 'Calculated amount: {value} {unit}',
    'calculator.invalid': 'Enter valid numbers to calculate',
    'calculator.example': 'Example: 150, 200.5',
    'calculator.error.required': 'Both fields are required',
    'calculator.error.numeric': 'Values must be numeric',
    'calculator.error.positive': 'Values must be positive',
    'calculator.error.endGreater': 'Final number must be greater than initial',
    'calculator.error.exceedsMax': 'Calculated amount ({value}) exceeds the maximum allowed ({max})',
    'calculator.error.belowMin': 'Calculated amount ({value}) is below the minimum required ({min})',
    'calculator.error.returnExceeds': 'You cannot return more than consumed. Available to return: {available}',
    'calculator.error.insufficientStock': 'Insufficient stock. Available: {available}',
    'calculator.warning.large': 'Are you sure? The calculated amount is very large',
    'calculator.warning.stock80': 'You are consuming more than 80% of available stock',
    'calculator.warning.returnAll': 'You are returning everything consumed',
    'calculator.help.title': 'How does it work?',
    'calculator.help.button': 'Help',
    'calculator.help.buttonAria': 'Open help explaining the marker system',
    'calculator.help.content1': 'Use the printed numbering on the cable to enter start and end.',
    'calculator.help.content2': 'The system calculates length with precision from those markers.',
    'calculator.help.point1': 'Enter only positive numbers; decimals are accepted.',
    'calculator.help.point2': 'End must be greater than start to be valid.',
    'calculator.help.point3': 'Very large results will ask for confirmation.',

    // ===== ADMIN - TOOLS =====
    'admin.tools.title': 'Manage Tools',
    'admin.tools.addNew': 'Add New Tool',
    'admin.tools.backToDashboard': 'Back to Dashboard',
    'admin.tools.totalTools': 'Total Tools',
    'admin.tools.available': 'Available',
    'admin.tools.loaned': 'Loaned',
    'admin.tools.maintenance': 'Maintenance',
    'admin.tools.search': 'Search',
    'admin.tools.searchPlaceholder': 'Search by name, QR code, or serial number...',
    'admin.tools.filterByStatus': 'Filter by Status',
    'admin.tools.filterByCategory': 'Filter by Category',
    'admin.tools.allStatus': 'All Status',
    'admin.tools.allCategories': 'All Categories',
    'admin.tools.noCategoriesAvailable': 'No categories available',
    'admin.tools.activeFilters': 'Active filters:',
    'admin.tools.clearAll': 'Clear all',
    'admin.tools.noToolsFound': 'No Tools Found',
    'admin.tools.noToolsMatch': 'No tools match your search criteria.',
    'admin.tools.noToolsYet': 'No tools have been added yet.',
    'admin.tools.clearFilters': 'Clear Filters',
    'admin.tools.viewDetails': 'View Details',
    'admin.tools.qrCode': 'QR Code',
    'admin.tools.serial': 'Serial',
    'admin.tools.category': 'Category',
    'admin.tools.added': 'Added',
    'admin.tools.notes': 'Notes',
    'admin.tools.loadingTools': 'Loading tools...',
    'admin.tools.statusAvailable': 'Available',
    'admin.tools.statusLoaned': 'Loaned',
    'admin.tools.statusOutOfService': 'Out of Service',
    'admin.tools.statusLost': 'Lost',
    'admin.tools.statusDamaged': 'Damaged',

    // ===== ADMIN - USERS =====
    'admin.users.title': 'Manage Users',
    'admin.users.addNew': 'Add New User',
    'admin.users.totalUsers': 'Total Users',
    'admin.users.admins': 'Admins',
    'admin.users.regularUsers': 'Regular Users',
    'admin.users.search': 'Search',
    'admin.users.searchPlaceholder': 'Search by username or email...',
    'admin.users.filterByRole': 'Filter by Role',
    'admin.users.allRoles': 'All Roles',
    'admin.users.admin': 'Admin',
    'admin.users.user': 'User',
    'admin.users.viewProfile': 'View Profile',
    'admin.users.joined': 'Joined',
    'admin.users.noUsersFound': 'No Users Found',
    'admin.users.noUsersMatch': 'No users match your search criteria.',
    'admin.users.noUsersYet': 'No users have been added yet.',
    'admin.users.loadingUsers': 'Loading users...',
    'admin.users.email': 'Email',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.actions': 'Actions',

    // ===== ADMIN - REPORTS =====
    'admin.reports.title': 'Reports Center',
    'admin.reports.subtitle': 'Access detailed reports and system inventory analysis',
    'admin.reports.categories': 'Categories Dashboard',
    'admin.reports.categoriesDesc': 'Complete inventory view organized by categories with key metrics',
    'admin.reports.loans': 'Loans Reports',
    'admin.reports.loansDesc': 'Detailed analysis of loans, return rates and most active users',
    'admin.reports.tools': 'Tools Inventory Reports',
    'admin.reports.toolsDesc': 'Inventory status, utilization rates and tools requiring maintenance',
    'admin.reports.consumables': 'Materials Reports',
    'admin.reports.consumablesDesc': 'Usage analysis by category, stock levels and restocking projections',
    'admin.reports.purchases': 'Purchase Reports',
    'admin.reports.purchasesDesc': 'Purchase history and spending analysis',
    'admin.reports.about': 'About Reports',
    'admin.reports.aboutDesc': 'All reports include interactive visualizations, advanced filters and export options in multiple formats (PDF, Excel, CSV). Data is updated in real-time from the database.',
    'admin.reports.loading': 'Loading...',

    // ===== ADMIN - CONSUMABLES =====
    'admin.consumables.title': 'Materials Management',
    'admin.consumables.addItemType': 'Add Material Type',
    'admin.consumables.bulkImport': 'Bulk Import',
    'admin.consumables.search': 'Search',
    'admin.consumables.searchPlaceholder': 'Search by name or category...',
    'admin.consumables.filterByCategory': 'Filter by Category',
    'admin.consumables.allCategories': 'All Categories',
    'admin.consumables.noItemsFound': 'No Items Found',
    'admin.consumables.noItemsMatch': 'No items match your search criteria.',
    'admin.consumables.loadingItems': 'Loading items...',
    'admin.consumables.viewDetails': 'View Details',
    'admin.consumables.updateStock': 'Update Stock',

    // ===== ADMIN - LOANS =====
    'admin.loans.title': 'Manage Loans',
    'admin.loans.allLoans': 'All Loans',
    'admin.loans.search': 'Search',
    'admin.loans.searchPlaceholder': 'Search by user, tool, or serial number...',
    'admin.loans.filterByStatus': 'Filter by Status',
    'admin.loans.allStatus': 'All Status',
    'admin.loans.statusActive': 'Active',
    'admin.loans.statusReturned': 'Returned',
    'admin.loans.statusOverdue': 'Overdue',
    'admin.loans.noLoansFound': 'No Loans Found',
    'admin.loans.loadingLoans': 'Loading loans...',
    'admin.loans.viewDetails': 'View Details',
    'admin.loans.markAsReturned': 'Mark as Returned',
    'admin.loans.user': 'User',
    'admin.loans.tool': 'Tool',
    'admin.loans.loanDate': 'Loan Date',
    'admin.loans.dueDate': 'Due Date',
    'admin.loans.returnDate': 'Return Date',

    // ===== ADMIN - AUDIT =====
    'admin.audit.title': 'Audit Log',
    'admin.audit.subtitle': 'System activity and changes log',
    'admin.audit.action': 'Action',
    'admin.audit.user': 'User',
    'admin.audit.timestamp': 'Timestamp',
    'admin.audit.details': 'Details',
    'admin.audit.ipAddress': 'IP Address',
    'admin.audit.userAgent': 'User Agent',
    'admin.audit.filterByAction': 'Filter by Action',
    'admin.audit.allActions': 'All Actions',
    'admin.audit.search': 'Search',
    'admin.audit.searchPlaceholder': 'Search by user or action...',
    'admin.audit.noLogsFound': 'No Logs Found',
    'admin.audit.loadingLogs': 'Loading logs...',

    // ===== STATUS LABELS =====
    'status.available': 'Available',
    'status.loaned': 'Loaned',
    'status.outOfService': 'Out of Service',
    'status.lost': 'Lost',
    'status.damaged': 'Damaged',
    'status.pending': 'Pending',
    'status.fulfilled': 'Fulfilled',
    'status.cancelled': 'Cancelled',
    'status.partial': 'Partially Fulfilled',
    'status.inStock': 'In Stock',
    'status.outOfStock': 'Out of Stock',
    'status.lowStock': 'Low Stock',
    'status.backorder': 'Backorder',

    // ===== BULK IMPORT =====
    'bulkImport.title': 'Bulk Import Materials',
    'bulkImport.button': 'Bulk Import',
    'bulkImport.selectFile': 'Select CSV File',
    'bulkImport.dragDrop': 'or drag and drop',
    'bulkImport.fileFormat': 'CSV file with columns: name, description, category, current_stock, minimum_threshold',
    'bulkImport.downloadTemplate': 'Download Template',
    'bulkImport.uploading': 'Uploading...',
    'bulkImport.processing': 'Processing...',
    'bulkImport.success': 'Successfully imported {count} items',
    'bulkImport.error': 'Error importing file',
    'bulkImport.close': 'Close',
    'bulkImport.cancel': 'Cancel',
    'bulkImport.import': 'Import',

    // ===== LANDING PAGE =====
    'landing.nav.features': 'Features',
    'landing.nav.benefits': 'Benefits',
    'landing.nav.contact': 'Contact',
    'landing.nav.login': 'Login',
    'landing.hero.title': 'Educational Inventory Management System',
    'landing.hero.subtitle': 'Efficient control of tools and consumables for educational institutions',
    'landing.hero.cta': 'Get Started',
    'landing.features.title': 'Key Features',
    'landing.features.qr': 'QR Code Scanning',
    'landing.features.qrDesc': 'Fast and accurate tool tracking',
    'landing.features.realtime': 'Real-time Tracking',
    'landing.features.realtimeDesc': 'Know the status of your inventory at all times',
    'landing.features.reports': 'Detailed Reports',
    'landing.features.reportsDesc': 'Analytics and insights for better decisions',
    'landing.features.management': 'Easy Management',
    'landing.features.managementDesc': 'Intuitive interface for managing tools and materials',
    'landing.benefits.title': 'Benefits',
    'landing.benefits.efficiency': 'Increased Efficiency',
    'landing.benefits.efficiencyDesc': 'Reduce time spent on inventory management',
    'landing.benefits.accuracy': 'Improved Accuracy',
    'landing.benefits.accuracyDesc': 'Minimize errors with automated tracking',
    'landing.benefits.visibility': 'Better Visibility',
    'landing.benefits.visibilityDesc': 'Real-time insights into your inventory',
    'landing.cta.title': 'Ready to optimize your inventory?',
    'landing.cta.subtitle': 'Join educational institutions already using our system',
    'landing.cta.button': 'Start Now',
    'landing.footer.rights': 'All rights reserved',
    'landing.footer.about': 'About',
    'landing.footer.contact': 'Contact',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.terms': 'Terms of Service',

    // ===== LOGIN PAGE =====
    'login.title': 'Login',
    'login.welcome': 'Welcome back',
    'login.subtitle': 'Enter your credentials to access',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Enter your username',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.button': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.error': 'Invalid credentials',
    'login.errorGeneric': 'An error occurred. Please try again.',
    'login.required': 'All fields are required',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': 'Don\'t have an account?',
    'login.signUp': 'Sign up',

    // ===== BAG COMPONENT =====
    'bag.title': 'Loan Bag',
    'bag.items': 'Items',
    'bag.empty': 'Your bag is empty',
    'bag.emptyDesc': 'Scan tools to add them to your loan bag',
    'bag.viewBag': 'View Bag',
    'bag.clearAll': 'Clear All',
    'bag.confirmLoan': 'Confirm Loan',
    'bag.remove': 'Remove',
    'bag.itemAdded': 'Item added to bag',
    'bag.itemRemoved': 'Item removed from bag',
    'bag.tooltip': 'Loan Bag',

    // ===== CART COMPONENT =====
    'cart.title': 'Request Cart',
    'cart.items': 'Items',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': 'Scan materials to add them to your request cart',
    'cart.viewCart': 'View Cart',
    'cart.clearAll': 'Clear All',
    'cart.confirmRequest': 'Confirm Request',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.total': 'Total Items',
    'cart.tooltip': 'Request Cart',

    // ===== VAULT COMPONENT =====
    'vault.title': 'Return Vault',
    'vault.items': 'Items',
    'vault.empty': 'Your vault is empty',
    'vault.emptyDesc': 'Scan tools to add them to your return vault',
    'vault.viewVault': 'View Vault',
    'vault.clearAll': 'Clear All',
    'vault.confirmReturn': 'Confirm Return',
    'vault.remove': 'Remove',
    'vault.itemAdded': 'Item added to vault',
    'vault.itemRemoved': 'Item removed from vault',
    'vault.tooltip': 'Return Vault',

    // ===== LOAN CONFIRMATION MODAL =====
    'loanConfirmation.title': 'Confirm Loan',
    'loanConfirmation.dueDate': 'Due Date',
    'loanConfirmation.selectDate': 'Select due date',
    'loanConfirmation.notes': 'Notes',
    'loanConfirmation.notesPlaceholder': 'Add any notes about this loan (optional)',
    'loanConfirmation.itemsToLoan': 'Items to Loan',
    'loanConfirmation.cancel': 'Cancel',
    'loanConfirmation.confirm': 'Confirm Loan',
    'loanConfirmation.confirming': 'Confirming...',
    'loanConfirmation.success': 'Loan confirmed successfully',
    'loanConfirmation.error': 'Failed to confirm loan',

    // ===== SCANNER COMPONENT =====
    'scanner.batch.title': 'Batch Scanning',
    'scanner.batch.mode': 'Batch Mode',
    'scanner.batch.count': 'Scanned: {count}',
    'scanner.batch.confirm': 'Confirm Batch',
    'scanner.batch.clear': 'Clear Batch',
    'scanner.batch.empty': 'No items scanned',
    'scanner.quantity.title': 'Enter Quantity',
    'scanner.quantity.label': 'Quantity',
    'scanner.quantity.placeholder': 'Enter quantity',
    'scanner.quantity.confirm': 'Confirm',
    'scanner.quantity.cancel': 'Cancel',
    'scanner.quantity.invalid': 'Please enter a valid quantity',
    'scanner.quantity.required': 'Quantity is required',
    'scanner.multiMode.single': 'Single Mode',
    'scanner.multiMode.batch': 'Batch Mode',
    'scanner.multiMode.tooltip': 'Switch scanning mode',
    'scanner.error.notFound': 'Item not found',
    'scanner.error.alreadyScanned': 'Item already scanned',
    'scanner.error.unavailable': 'Item is not available',
    'scanner.error.invalidQR': 'Invalid QR code',
    'scanner.error.cameraPermission': 'Camera permission denied',
    'scanner.error.cameraNotFound': 'No camera found',

    // ===== BULK IMPORT (Extended) =====
    'bulkImport.instructions': 'Upload a CSV file to import multiple items at once',
    'bulkImport.step1': 'Download the template',
    'bulkImport.step2': 'Fill in your data',
    'bulkImport.step3': 'Upload the completed file',
    'bulkImport.validating': 'Validating...',
    'bulkImport.rowsProcessed': 'Rows processed: {count}',
    'bulkImport.errors': 'Errors found',
    'bulkImport.errorRow': 'Row {row}: {error}',
    'bulkImport.preview': 'Preview',
    'bulkImport.previewTitle': 'Preview Import',
    'bulkImport.previewDesc': 'Review the items before importing',
    'bulkImport.confirmImport': 'Confirm Import',
    'bulkImport.backToUpload': 'Back to Upload',
    'bulkImport.duplicateFound': 'Duplicate item found',
    'bulkImport.invalidFormat': 'Invalid file format',

    // ===== FORM VALIDATION =====
    'form.required': 'This field is required',
    'form.invalidEmail': 'Invalid email address',
    'form.invalidNumber': 'Please enter a valid number',
    'form.minLength': 'Must be at least {min} characters',
    'form.maxLength': 'Must be no more than {max} characters',
    'form.minValue': 'Must be at least {min}',
    'form.maxValue': 'Must be no more than {max}',
    'form.invalidDate': 'Invalid date',
    'form.pastDate': 'Date cannot be in the past',
    'form.futureDate': 'Date cannot be in the future',
    'form.invalidUrl': 'Invalid URL',
    'form.passwordMismatch': 'Passwords do not match',
    'form.saving': 'Saving...',

    // ===== ELECTRONICS =====
    'electronics.title': 'Electronic Devices',
    'electronics.addNew': 'Add New Device',
    'electronics.backToDashboard': 'Back to Dashboard',
    'electronics.totalDevices': 'Total Devices',
    'electronics.available': 'Available',
    'electronics.loaned': 'Loaned',
    'electronics.maintenance': 'Maintenance',
    'electronics.search': 'Search',
    'electronics.searchPlaceholder': 'Search by name, brand, model, or serial...',
    'electronics.filterByStatus': 'Filter by Status',
    'electronics.filterByCategory': 'Filter by Category',
    'electronics.allStatus': 'All Status',
    'electronics.allCategories': 'All Categories',
    'electronics.activeFilters': 'Active filters:',
    'electronics.clearAll': 'Clear all',
    'electronics.noDevicesFound': 'No Devices Found',
    'electronics.noDevicesMatch': 'No devices match your search criteria.',
    'electronics.noDevicesYet': 'No electronic devices have been added yet.',
    'electronics.clearFilters': 'Clear Filters',
    'electronics.viewDetails': 'View Details',
    'electronics.brand': 'Brand',
    'electronics.model': 'Model',
    'electronics.serial': 'Serial',
    'electronics.category': 'Category',
    'electronics.added': 'Added',
    'electronics.notes': 'Notes',
    'electronics.loadingDevices': 'Loading devices...',
    'electronics.deviceDetails': 'Device Details',
    'electronics.specifications': 'Specifications',
    'electronics.conditionNotes': 'Condition Notes',
    'electronics.currentlyLoaned': 'Currently Loaned',
    'electronics.editDevice': 'Edit Device',
    'electronics.deleteDevice': 'Delete Device',
    'electronics.deleting': 'Deleting...',
    'electronics.confirmDelete': 'Confirm Deletion',
    'electronics.confirmDeleteMessage': 'Are you sure you want to delete this device? This action cannot be undone.',
    'electronics.cannotDeleteWithLoan': 'Cannot delete device with active loan',
    'electronics.createDevice': 'Create Device',
    'electronics.updateDevice': 'Update Device',
    'electronics.creating': 'Creating...',
    'electronics.updating': 'Updating...',
    'electronics.deviceCreated': 'Device created successfully!',
    'electronics.deviceUpdated': 'Device updated successfully!',
    'electronics.deviceDeleted': 'Device deleted successfully!',
    'electronics.errorCreating': 'Failed to create device',
    'electronics.errorUpdating': 'Failed to update device',
    'electronics.errorDeleting': 'Failed to delete device',
    'electronics.errorLoading': 'Failed to load device',
    'electronics.name': 'Name',
    'electronics.description': 'Description',
    'electronics.status': 'Status',
    'electronics.conditionNotesLabel': 'Condition Notes',
    'electronics.enterName': 'Enter device name',
    'electronics.enterDescription': 'Enter device description',
    'electronics.enterBrand': 'e.g., Apple, Dell, HP',
    'electronics.enterModel': 'e.g., MacBook Pro, Latitude 5420',
    'electronics.enterSerial': 'Enter serial number',
    'electronics.enterConditionNotes': 'Any notes about the device condition',
    'electronics.dangerZone': 'Danger Zone',
    'electronics.dangerZoneDesc': 'Once you delete a device, there is no going back. Please be certain.',
    'electronics.tips': 'Tips',
    'electronics.tip1': 'A QR code will be automatically generated for this device',
    'electronics.tip2': 'Brand and model information helps with identification',
    'electronics.tip3': 'Serial numbers are useful for warranty and tracking',
    'electronics.tip4': 'Add condition notes for any existing issues or special characteristics',

    // Electronics Categories
    'electronics.category.laptops': 'Laptops',
    'electronics.category.tablets': 'Tablets',
    'electronics.category.smartphones': 'Smartphones',
    'electronics.category.peripherals': 'Peripherals',
    'electronics.category.digital': 'Digital',
    'electronics.category.others': 'Others',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.scanner': 'Escáner',
    'nav.myLoans': 'Panel de Préstamos',
    'nav.consumables': 'Materiales y Reservas',
    'nav.admin': 'Admin',
    'nav.profile': 'Perfil',

    // Dashboard
    'dashboard.title': 'Panel Principal',
    'dashboard.hello': 'Hola',
    'dashboard.notifications': 'Notificaciones',
    'dashboard.userMenu': 'Menú de usuario',
    'dashboard.profile': 'Perfil',
    'dashboard.scanToLoan': 'Escanear para Prestar',
    'dashboard.scanToReturn': 'Escanear para Devolver',
    'dashboard.requestSupplies': 'Solicitar Materiales',
    'dashboard.myLoans': 'Panel de Préstamos',
    'dashboard.activeLoans': 'Préstamos Activos',
    'dashboard.recentLoans': 'Préstamos Recientes',
    'dashboard.welcome': 'Escanea códigos QR para prestar o devolver herramientas',
    'dashboard.noActiveLoans': 'Sin Préstamos Activos',
    'dashboard.noActiveLoansDesc': 'No tienes herramientas prestadas actualmente.',

    // Navigation
    'navigation.home': 'Inicio',
    'navigation.scanner': 'Escáner',
    'navigation.loans': 'Préstamos',
    'navigation.consumables': 'Materiales y Reservas',
    'navigation.profile': 'Perfil',

    // Scanner
    'scanner.title': 'Escáner',
    'scanner.scanSupplies': 'Solicitar Materiales',
    'scanner.scanSuppliesDesc': 'Escanea códigos QR de materiales para registrar uso',
    'scanner.scanTools': 'Escanear Herramientas',
    'scanner.scanToolsDesc': 'Escanea códigos QR de herramientas para prestar o devolver',
    'scanner.manualEntry': 'Entrada Manual',
    'scanner.manualEntryDesc': 'Ingresa el código QR manualmente',
    'scanner.scanning': 'Escaneando...',
    'scanner.cancel': 'Cancelar Escaneo',
    'scanner.processing': 'Procesando...',
    'scanner.returnConsumables': 'Devolver Materiales',
    'scanner.returnConsumablesDesc': 'Devuelve materiales no utilizados de tus prácticas',

    // Returns
    'returns.title': 'Devolver Materiales',
    'returns.selectDate': 'Seleccionar Fecha de Consumo',
    'returns.noConsumptions': 'No hay consumos en esta fecha',
    'returns.addToCart': 'Agregar al Carrito',
    'returns.confirmReturn': 'Confirmar Devolución',
    'returns.returnSuccess': 'Devolución procesada exitosamente',
    'returns.maxReturnable': 'Máximo devolvible',
    'returns.consumed': 'Consumido',
    'returns.returned': 'Devuelto',
    'returns.returnable': 'Disponible para devolver',
    'returns.howItWorks': '¿Cómo funciona?',
    'returns.step1': 'Selecciona la fecha en que consumiste los items',
    'returns.step2': 'Elige los items que deseas devolver y las cantidades',
    'returns.step3': 'Agrégalos al carrito de devolución',
    'returns.step4': 'Confirma la devolución para actualizar el stock',
    'returns.selectDatePrompt': 'Selecciona una fecha',
    'returns.selectDateDesc': 'Elige una fecha de consumo para ver los items que puedes devolver',
    'returns.itemsConsumed': 'Items Consumidos',
    'returns.loadingItems': 'Cargando items...',
    'returns.returnCart': 'Carrito de Devolución',
    'returns.totalToReturn': 'Total a devolver:',
    'returns.emptyCart': 'Vaciar Carrito',
    'returns.confirmReturnBtn': 'Confirmar Devolución',
    'returns.processing': 'Procesando...',
    'returns.noItemsInCart': 'No hay items en el carrito de devolución',
    'returns.alreadyReturned': 'Ya has devuelto todo lo consumido',
    'returns.noRecentConsumptions': 'No hay consumos recientes',
    'returns.noConsumptionsDesc': 'No tienes consumos en los últimos 30 días para devolver.',
    'returns.loadingHistory': 'Cargando historial...',
    'returns.refresh': 'Actualizar',
    'returns.consumptionDate': 'Fecha consumo:',
    'returns.items': 'Items:',
    'returns.totalConsumed': 'Consumido:',
    'returns.totalReturnable': 'Devolvible:',
    'returns.units': 'unidades',

    // My Loans
    'myLoans.title': 'Panel de Préstamos',
    'myLoans.myLoans': 'Mis Préstamos',
    'myLoans.allActiveLoans': 'Préstamos Generales Activos',
    'myLoans.availableTools': 'Herramientas Disponibles',
    'myLoans.scanToReturn': 'Escanear para Devolver',
    'myLoans.active': 'Activos',
    'myLoans.overdue': 'Vencidos',
    'myLoans.returned': 'Devueltos',
    'myLoans.total': 'Total',
    'myLoans.activeLoans': 'Préstamos Activos',
    'myLoans.history': 'Historial de Préstamos',
    'myLoans.consumables': 'Historial de Materiales',
    'myLoans.noActiveLoans': 'Sin Préstamos Activos',
    'myLoans.noActiveLoansDes': 'No tienes herramientas prestadas actualmente.',
    'myLoans.noActiveLoansDesc': 'No hay préstamos activos en el sistema',
    'myLoans.scanToLoanTool': 'Escanear para Prestar Herramienta',
    'myLoans.noHistory': 'Sin Historial de Préstamos',
    'myLoans.noHistoryDesc': 'Tu historial de préstamos aparecerá aquí.',
    'myLoans.noConsumables': 'Sin Historial de Materiales',
    'myLoans.noConsumablesDesc': 'No has solicitado ningún material aún.',
    'myLoans.scanToConsume': 'Solicitar Materiales',
    'myLoans.backToDashboard': 'Volver al Panel',
    'myLoans.returning': 'Devolviendo...',
    'myLoans.return': 'Devolver',
    'myLoans.scanRequiredTitle': 'Escaneo Obligatorio para Devoluciones',
    'myLoans.scanRequiredDesc': 'Para devolver herramientas, por favor usa el escáner QR',
    'myLoans.allCategories': 'Todas',
    'myLoans.totalAvailable': 'Total de herramientas disponibles',
    'myLoans.available': 'disponibles',
    'myLoans.noAvailableTools': 'No hay herramientas disponibles',
    'myLoans.noAvailableToolsDesc': 'Todas las herramientas están prestadas',

    // Consumables
    'consumables.title': 'Materiales',
    'consumables.scanQR': 'Escanear QR',
    'consumables.management': 'Gestión de Materiales',
    'consumables.addItemType': 'Agregar Tipo de Material',
    'consumables.backToDashboard': 'Volver al Panel',
    'consumables.totalItems': 'Materiales Totales',
    'consumables.outOfStock': 'Sin Stock',
    'consumables.lowStock': 'Stock Bajo',
    'consumables.backorders': 'Pedidos Pendientes',
    'consumables.inventory': 'Inventario',
    'consumables.currentStock': 'Stock Actual',
    'consumables.minimumThreshold': 'Umbral Mínimo',
    'consumables.quantity': 'Cantidad',
    'consumables.quantityToConsume': 'Cantidad a Solicitar',
    'consumables.consume': 'Solicitar',
    'consumables.date': 'Fecha',
    'consumables.notes': 'Notas',
    'consumables.scanAnother': 'Escanear Otro Material',
    'consumables.inStock': 'En Stock',
    'consumables.cannotConsume': 'Este material está agotado y no se puede solicitar',

    // Loan Details
    'loan.serial': 'Serial',
    'loan.loaned': 'Prestado',
    'loan.due': 'Vencimiento',
    'loan.returned': 'Devuelto',
    'loan.notes': 'Notas',
    'loan.lost': 'Perdido',
    'loan.overdue': 'Vencido',
    'loan.unknownTool': 'Herramienta Desconocida',

    // Consumable Details
    'consumable.consumed': 'Consumido',
    'consumable.at': 'a las',
    'consumable.available': 'Disponible',
    'consumable.units': 'unidades',
    'consumable.pieces': 'piezas',

    // Admin Dashboard
    'admin.dashboard': 'Panel de Administración',
    'admin.manageTools': 'Gestionar Herramientas',
    'admin.availableTools': 'Herramientas Disponibles',
    'admin.activeLoans': 'Préstamos Activos',
    'admin.overdueLoans': 'Préstamos Vencidos',
    'admin.totalUsers': 'Usuarios Totales',
    'admin.consumableInventory': 'Inventario de Materiales',
    'admin.lowStockItems': 'Materiales con Stock Bajo',
    'admin.totalElectronics': 'Dispositivos Electrónicos',
    'admin.manageElectronics': 'Gestionar Electrónicos',
    'admin.manageElectronicsDesc': 'Administrar dispositivos electrónicos',
    'admin.systemHealth': 'Salud del Sistema',
    'admin.good': 'Bueno',
    'admin.quickActions': 'Acciones Rápidas',
    'admin.addNewTool': 'Agregar Nueva Herramienta',
    'admin.addItemType': 'Agregar Tipo de Artículo',
    'admin.addUser': 'Agregar Usuario',
    'admin.generateReport': 'Reportes',
    'admin.manageToolsBtn': 'Gestionar Herramientas',
    'admin.manageUsers': 'Gestionar Usuarios',
    'admin.quickAccessDesc': 'Accede rápidamente a las secciones principales del sistema',
    'admin.manageToolsDesc': 'Ver, crear y administrar',
    'admin.manageUsersDesc': 'Ver, crear y administrar',
    'admin.manageMaterialsDesc': 'Stock y reabastecimiento',
    'admin.reportsDesc': 'Análisis y estadísticas',
    'admin.advancedConfig': 'Configuración Avanzada',
    'admin.advancedConfigDesc': 'Opciones de configuración y herramientas para usuarios avanzados',
    'admin.manageItemTypes': 'Gestionar Tipos de Items',
    'admin.manageItemTypesDesc': 'Crear/editar tipos manualmente',
    'admin.invoiceReports': 'Reportes de Facturas',
    'admin.invoiceReportsDesc': 'Reportes de compras y facturas',
    'admin.auditLogs': 'Registros de Auditoría',
    'admin.auditLogsDesc': 'Historial de cambios del sistema',
    'admin.systemInfo': 'Información del Sistema',
    'admin.databaseStatus': 'Estado de la Base de Datos',
    'admin.databaseConnected': 'Conectada y Operativa',
    'admin.dataRefresh': 'Actualización de Datos',
    'admin.autoUpdates': 'Actualización automática cada minuto',
    'admin.realTimeStats': 'Estadísticas en Tiempo Real',
    'admin.liveData': 'Datos en vivo desde la base de datos',
    'admin.lastUpdated': 'Última Actualización',

    // My Requests
    'requests.title': 'Mis Solicitudes',
    'requests.mySupplyRequests': 'Mis Solicitudes de Materiales',
    'requests.requestSupplies': 'Solicitar Materiales',
    'requests.active': 'Activas',
    'requests.backorders': 'Pedidos Pendientes',
    'requests.fulfilled': 'Cumplidas',
    'requests.total': 'Total',
    'requests.activeRequests': 'Solicitudes Activas',
    'requests.history': 'Historial',
    'requests.aboutBackorders': 'Acerca de los Pedidos Pendientes',
    'requests.backordersInfo': 'Los artículos marcados como "Pendiente" son pedidos pendientes. Recibirás una notificación cuando haya stock disponible y tu solicitud sea cumplida. Las solicitudes se procesan en el orden en que fueron recibidas.',
    'requests.noActiveRequests': 'Sin Solicitudes Activas',
    'requests.noRequestHistory': 'Sin Historial de Solicitudes',
    'requests.noActiveRequestsDesc': 'No tienes solicitudes de materiales activas.',
    'requests.requestHistoryDesc': 'Tu historial de solicitudes aparecerá aquí.',
    'requests.backToDashboard': 'Volver al Panel',
    'requests.requested': 'Solicitado',
    'requests.fulfilledQty': 'Cumplido',
    'requests.remaining': 'Restante',
    'requests.requestedDate': 'Solicitado',
    'requests.fulfilledDate': 'Cumplido',
    'requests.backorderNotice': '⏳ Este es un pedido pendiente - se te notificará cuando haya stock disponible',
    'requests.notesLabel': 'Notas',
    'requests.statusFulfilled': 'Cumplido',
    'requests.statusPartial': 'Parcialmente Cumplido',
    'requests.statusCancelled': 'Cancelado',
    'requests.statusPending': 'Pendiente',
    'requests.cancel': 'Cancelar',
    'requests.cancelling': 'Cancelando...',
    'requests.loadingRequests': 'Cargando solicitudes...',

    // Reports
    'reports.title': 'Generar Reporte',
    'reports.selectType': 'Seleccionar Tipo de Reporte',
    'reports.dateRange': 'Rango de Fechas',
    'reports.startDate': 'Fecha de Inicio',
    'reports.endDate': 'Fecha de Fin',
    'reports.summary': 'Resumen del Reporte',
    'reports.reportType': 'Tipo de Reporte',
    'reports.period': 'Período',
    'reports.generate': 'Generar Reporte',
    'reports.generating': 'Generando...',
    'reports.pdfNote': 'El reporte se generará en formato PDF y se puede descargar o imprimir.',
    'reports.loansReport': 'Reporte de Préstamos',
    'reports.loansDesc': 'Resumen de todos los préstamos, devoluciones y artículos vencidos',
    'reports.toolsInventory': 'Inventario de Herramientas',
    'reports.toolsDesc': 'Estado actual e historial de todas las herramientas',
    'reports.consumablesReport': 'Reporte de Materiales',
    'reports.consumablesDesc': 'Niveles de stock y patrones de uso',
    'reports.usersReport': 'Reporte de Usuarios',
    'reports.usersDesc': 'Actividad de usuarios e historial de préstamos',
    'reports.auditLog': 'Registro de Auditoría',
    'reports.auditDesc': 'Actividad del sistema y registro de cambios',
    'reports.generatedSuccess': 'generado exitosamente!',
    'reports.generatedError': 'Error al generar el reporte',

    // Profile
    'profile.title': 'Perfil',
    'profile.language': 'Idioma',
    'profile.english': 'Inglés',
    'profile.spanish': 'Español',
    'profile.settings': 'Configuración',
    'profile.logout': 'Cerrar Sesión',
    'profile.changePassword': 'Cambiar Contraseña',

    // Change Password
    'changePassword.title': 'Cambiar Contraseña',
    'changePassword.description': 'Actualiza la contraseña de tu cuenta para mantenerla segura',
    'changePassword.currentPassword': 'Contraseña Actual',
    'changePassword.newPassword': 'Nueva Contraseña',
    'changePassword.confirmPassword': 'Confirmar Nueva Contraseña',
    'changePassword.enterCurrentPassword': 'Ingresa tu contraseña actual',
    'changePassword.enterNewPassword': 'Ingresa tu nueva contraseña',
    'changePassword.confirmNewPassword': 'Confirma tu nueva contraseña',
    'changePassword.passwordRequirements': 'La contraseña debe tener al menos 6 caracteres',
    'changePassword.changePassword': 'Cambiar Contraseña',
    'changePassword.changing': 'Cambiando...',
    'changePassword.success': '¡Contraseña cambiada exitosamente! Redirigiendo...',
    'changePassword.failed': 'Error al cambiar la contraseña',
    'changePassword.passwordsDoNotMatch': 'Las contraseñas no coinciden',
    'changePassword.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'changePassword.samePassword': 'La nueva contraseña debe ser diferente de la actual',
    'changePassword.unknownError': 'Ocurrió un error desconocido',

    // Notifications
    'notifications.noNotifications': 'Sin notificaciones',
    'notifications.markAllAsRead': 'Marcar todas como leídas',
    'notifications.justNow': 'Justo ahora',
    'notifications.all': 'Todas',
    'notifications.unread': 'No leídas',
    'notifications.allTypes': 'Todos los tipos',
    'notifications.info': 'Info',
    'notifications.success': 'Éxito',
    'notifications.warning': 'Advertencia',
    'notifications.error': 'Error',
    'notifications.noUnread': 'No hay notificaciones sin leer',
    'notifications.delete': 'Eliminar',
    'notifications.preferences': 'Preferencias de notificaciones',

    // Common
    'common.loading': 'Cargando...',
    'common.loadingLoans': 'Cargando préstamos...',
    'common.loadingInventory': 'Cargando inventario...',
    'common.loadingConsumptions': 'Cargando consumos...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.actions': 'Acciones',
    'common.close': 'Cerrar',
    'common.details': 'Detalles',
    'common.description': 'Descripción',
    'common.category': 'Categoría',
    'common.status': 'Estado',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.yes': 'Sí',
    'common.no': 'No',

    // ===== CALCULADORA DE MEDICIÓN DE CABLE =====
    'calculator.helperText': 'Ingresa la numeración que aparece en el cable',
    'calculator.initialLabel': 'Número Inicial',
    'calculator.finalLabel': 'Número Final',
    'calculator.segmentStartLabel': 'Numeración Inicial del Tramo',
    'calculator.segmentEndLabel': 'Numeración Final del Tramo',
    'calculator.calculated': 'Cantidad calculada: {value} {unit}',
    'calculator.invalid': 'Ingresa números válidos para calcular',
    'calculator.example': 'Ejemplo: 150, 200.5',
    'calculator.error.required': 'Ambos campos son requeridos',
    'calculator.error.numeric': 'Los valores deben ser numéricos',
    'calculator.error.positive': 'Los valores deben ser positivos',
    'calculator.error.endGreater': 'El número final debe ser mayor que el número inicial',
    'calculator.error.exceedsMax': 'La cantidad calculada ({value}) excede el máximo permitido ({max})',
    'calculator.error.belowMin': 'La cantidad calculada ({value}) es menor al mínimo requerido ({min})',
    'calculator.error.returnExceeds': 'No puedes devolver más de lo que consumiste. Disponible para devolver: {available}',
    'calculator.error.insufficientStock': 'Stock insuficiente. Disponible: {available}',
    'calculator.warning.large': '¿Estás seguro? La cantidad calculada es muy grande',
    'calculator.warning.stock80': 'Estás consumiendo más del 80% del stock disponible',
    'calculator.warning.returnAll': 'Estás devolviendo todo lo consumido',
    'calculator.help.title': '¿Cómo funciona?',
    'calculator.help.button': 'Ayuda',
    'calculator.help.buttonAria': 'Abrir ayuda que explica el sistema de numeración',
    'calculator.help.content1': 'Usa la numeración impresa en el cable para ingresar inicio y final.',
    'calculator.help.content2': 'El sistema calcula la cantidad con precisión a partir de esas numeraciones.',
    'calculator.help.point1': 'Ingresa solo números positivos; se aceptan decimales.',
    'calculator.help.point2': 'El final debe ser mayor que el inicio para ser válido.',
    'calculator.help.point3': 'Resultados muy grandes solicitarán confirmación.',
    // ===== ADMIN - TOOLS =====
    'admin.tools.title': 'Gestionar Herramientas',
    'admin.tools.addNew': 'Agregar Nueva Herramienta',
    'admin.tools.backToDashboard': 'Volver al Panel',
    'admin.tools.totalTools': 'Herramientas Totales',
    'admin.tools.available': 'Disponibles',
    'admin.tools.loaned': 'Prestadas',
    'admin.tools.maintenance': 'Mantenimiento',
    'admin.tools.search': 'Buscar',
    'admin.tools.searchPlaceholder': 'Buscar por nombre, código QR o número de serie...',
    'admin.tools.filterByStatus': 'Filtrar por Estado',
    'admin.tools.filterByCategory': 'Filtrar por Categoría',
    'admin.tools.allStatus': 'Todos los Estados',
    'admin.tools.allCategories': 'Todas las Categorías',
    'admin.tools.noCategoriesAvailable': 'No hay categorías disponibles',
    'admin.tools.activeFilters': 'Filtros activos:',
    'admin.tools.clearAll': 'Limpiar todo',
    'admin.tools.noToolsFound': 'No se Encontraron Herramientas',
    'admin.tools.noToolsMatch': 'No hay herramientas que coincidan con tu búsqueda.',
    'admin.tools.noToolsYet': 'No se han agregado herramientas aún.',
    'admin.tools.clearFilters': 'Limpiar Filtros',
    'admin.tools.viewDetails': 'Ver Detalles',
    'admin.tools.qrCode': 'Código QR',
    'admin.tools.serial': 'Serial',
    'admin.tools.category': 'Categoría',
    'admin.tools.added': 'Agregado',
    'admin.tools.notes': 'Notas',
    'admin.tools.loadingTools': 'Cargando herramientas...',
    'admin.tools.statusAvailable': 'Disponible',
    'admin.tools.statusLoaned': 'Prestada',
    'admin.tools.statusOutOfService': 'Fuera de Servicio',
    'admin.tools.statusLost': 'Perdida',
    'admin.tools.statusDamaged': 'Dañada',

    // ===== ADMIN - USERS =====
    'admin.users.title': 'Gestionar Usuarios',
    'admin.users.addNew': 'Agregar Nuevo Usuario',
    'admin.users.totalUsers': 'Usuarios Totales',
    'admin.users.admins': 'Administradores',
    'admin.users.regularUsers': 'Usuarios Regulares',
    'admin.users.search': 'Buscar',
    'admin.users.searchPlaceholder': 'Buscar por nombre de usuario o email...',
    'admin.users.filterByRole': 'Filtrar por Rol',
    'admin.users.allRoles': 'Todos los Roles',
    'admin.users.admin': 'Administrador',
    'admin.users.user': 'Usuario',
    'admin.users.viewProfile': 'Ver Perfil',
    'admin.users.joined': 'Registrado',
    'admin.users.noUsersFound': 'No se Encontraron Usuarios',
    'admin.users.noUsersMatch': 'No hay usuarios que coincidan con tu búsqueda.',
    'admin.users.noUsersYet': 'No se han agregado usuarios aún.',
    'admin.users.loadingUsers': 'Cargando usuarios...',
    'admin.users.email': 'Correo Electrónico',
    'admin.users.role': 'Rol',
    'admin.users.status': 'Estado',
    'admin.users.actions': 'Acciones',

    // ===== ADMIN - REPORTS =====
    'admin.reports.title': 'Centro de Reportes',
    'admin.reports.subtitle': 'Accede a reportes detallados y análisis del sistema de inventario',
    'admin.reports.categories': 'Dashboard de Categorías',
    'admin.reports.categoriesDesc': 'Vista completa del inventario organizado por categorías con métricas clave',
    'admin.reports.loans': 'Reportes de Préstamos',
    'admin.reports.loansDesc': 'Análisis detallado de préstamos, tasas de devolución y usuarios más activos',
    'admin.reports.tools': 'Reportes de Inventario de Herramientas',
    'admin.reports.toolsDesc': 'Estado del inventario, tasas de utilización y herramientas que requieren mantenimiento',
    'admin.reports.consumables': 'Reportes de Consumibles',
    'admin.reports.consumablesDesc': 'Análisis de consumo por categoría, niveles de stock y proyecciones de reabastecimiento',
    'admin.reports.purchases': 'Reportes de Compras',
    'admin.reports.purchasesDesc': 'Historial de compras y análisis de gastos',
    'admin.reports.about': 'Acerca de los Reportes',
    'admin.reports.aboutDesc': 'Todos los reportes incluyen visualizaciones interactivas, filtros avanzados y opciones de exportación en múltiples formatos (PDF, Excel, CSV). Los datos se actualizan en tiempo real desde la base de datos.',
    'admin.reports.loading': 'Cargando...',

    // ===== ADMIN - CONSUMABLES =====
    'admin.consumables.title': 'Gestión de Materiales',
    'admin.consumables.addItemType': 'Agregar Tipo de Material',
    'admin.consumables.bulkImport': 'Importación Masiva',
    'admin.consumables.search': 'Buscar',
    'admin.consumables.searchPlaceholder': 'Buscar por nombre o categoría...',
    'admin.consumables.filterByCategory': 'Filtrar por Categoría',
    'admin.consumables.allCategories': 'Todas las Categorías',
    'admin.consumables.noItemsFound': 'No se Encontraron Artículos',
    'admin.consumables.noItemsMatch': 'No hay artículos que coincidan con tu búsqueda.',
    'admin.consumables.loadingItems': 'Cargando artículos...',
    'admin.consumables.viewDetails': 'Ver Detalles',
    'admin.consumables.updateStock': 'Actualizar Stock',

    // ===== ADMIN - LOANS =====
    'admin.loans.title': 'Gestionar Préstamos',
    'admin.loans.allLoans': 'Todos los Préstamos',
    'admin.loans.search': 'Buscar',
    'admin.loans.searchPlaceholder': 'Buscar por usuario, herramienta o número de serie...',
    'admin.loans.filterByStatus': 'Filtrar por Estado',
    'admin.loans.allStatus': 'Todos los Estados',
    'admin.loans.statusActive': 'Activo',
    'admin.loans.statusReturned': 'Devuelto',
    'admin.loans.statusOverdue': 'Vencido',
    'admin.loans.noLoansFound': 'No se Encontraron Préstamos',
    'admin.loans.loadingLoans': 'Cargando préstamos...',
    'admin.loans.viewDetails': 'Ver Detalles',
    'admin.loans.markAsReturned': 'Marcar como Devuelto',
    'admin.loans.user': 'Usuario',
    'admin.loans.tool': 'Herramienta',
    'admin.loans.loanDate': 'Fecha de Préstamo',
    'admin.loans.dueDate': 'Fecha de Vencimiento',
    'admin.loans.returnDate': 'Fecha de Devolución',

    // ===== ADMIN - AUDIT =====
    'admin.audit.title': 'Registro de Auditoría',
    'admin.audit.subtitle': 'Registro de actividad y cambios del sistema',
    'admin.audit.action': 'Acción',
    'admin.audit.user': 'Usuario',
    'admin.audit.timestamp': 'Fecha y Hora',
    'admin.audit.details': 'Detalles',
    'admin.audit.ipAddress': 'Dirección IP',
    'admin.audit.userAgent': 'Agente de Usuario',
    'admin.audit.filterByAction': 'Filtrar por Acción',
    'admin.audit.allActions': 'Todas las Acciones',
    'admin.audit.search': 'Buscar',
    'admin.audit.searchPlaceholder': 'Buscar por usuario o acción...',
    'admin.audit.noLogsFound': 'No se Encontraron Registros',
    'admin.audit.loadingLogs': 'Cargando registros...',

    // ===== STATUS LABELS =====
    'status.available': 'Disponible',
    'status.loaned': 'Prestada',
    'status.outOfService': 'Fuera de Servicio',
    'status.lost': 'Perdida',
    'status.damaged': 'Dañada',
    'status.pending': 'Pendiente',
    'status.fulfilled': 'Cumplido',
    'status.cancelled': 'Cancelado',
    'status.partial': 'Parcialmente Cumplido',
    'status.inStock': 'En Stock',
    'status.outOfStock': 'Sin Stock',
    'status.lowStock': 'Stock Bajo',
    'status.backorder': 'Pedido Pendiente',

    // ===== BULK IMPORT =====
    'bulkImport.title': 'Importación Masiva de Materiales',
    'bulkImport.button': 'Importación Masiva',
    'bulkImport.selectFile': 'Seleccionar Archivo CSV',
    'bulkImport.dragDrop': 'o arrastra y suelta',
    'bulkImport.fileFormat': 'Archivo CSV con columnas: name, description, category, current_stock, minimum_threshold',
    'bulkImport.downloadTemplate': 'Descargar Plantilla',
    'bulkImport.uploading': 'Subiendo...',
    'bulkImport.processing': 'Procesando...',
    'bulkImport.success': '{count} artículos importados exitosamente',
    'bulkImport.error': 'Error al importar archivo',
    'bulkImport.close': 'Cerrar',
    'bulkImport.cancel': 'Cancelar',
    'bulkImport.import': 'Importar',

    // ===== LANDING PAGE =====
    'landing.nav.features': 'Características',
    'landing.nav.benefits': 'Beneficios',
    'landing.nav.contact': 'Contacto',
    'landing.nav.login': 'Iniciar Sesión',
    'landing.hero.title': 'Sistema de Gestión de Inventario Educativo',
    'landing.hero.subtitle': 'Control eficiente de herramientas y consumibles para instituciones educativas',
    'landing.hero.cta': 'Comenzar',
    'landing.features.title': 'Características Principales',
    'landing.features.qr': 'Escaneo de Códigos QR',
    'landing.features.qrDesc': 'Seguimiento rápido y preciso de herramientas',
    'landing.features.realtime': 'Seguimiento en Tiempo Real',
    'landing.features.realtimeDesc': 'Conoce el estado de tu inventario en todo momento',
    'landing.features.reports': 'Reportes Detallados',
    'landing.features.reportsDesc': 'Análisis e información para mejores decisiones',
    'landing.features.management': 'Gestión Fácil',
    'landing.features.managementDesc': 'Interfaz intuitiva para gestionar herramientas y materiales',
    'landing.benefits.title': 'Beneficios',
    'landing.benefits.efficiency': 'Mayor Eficiencia',
    'landing.benefits.efficiencyDesc': 'Reduce el tiempo dedicado a la gestión de inventario',
    'landing.benefits.accuracy': 'Mejor Precisión',
    'landing.benefits.accuracyDesc': 'Minimiza errores con seguimiento automatizado',
    'landing.benefits.visibility': 'Mejor Visibilidad',
    'landing.benefits.visibilityDesc': 'Información en tiempo real sobre tu inventario',
    'landing.cta.title': '¿Listo para optimizar tu inventario?',
    'landing.cta.subtitle': 'Únete a las instituciones educativas que ya usan nuestro sistema',
    'landing.cta.button': 'Comenzar Ahora',
    'landing.footer.rights': 'Todos los derechos reservados',
    'landing.footer.about': 'Acerca de',
    'landing.footer.contact': 'Contacto',
    'landing.footer.privacy': 'Política de Privacidad',
    'landing.footer.terms': 'Términos de Servicio',

    // ===== LOGIN PAGE =====
    'login.title': 'Iniciar Sesión',
    'login.welcome': 'Bienvenido de nuevo',
    'login.subtitle': 'Ingresa tus credenciales para acceder',
    'login.username': 'Nombre de Usuario',
    'login.usernamePlaceholder': 'Ingresa tu nombre de usuario',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': 'Ingresa tu contraseña',
    'login.button': 'Iniciar Sesión',
    'login.loggingIn': 'Iniciando sesión...',
    'login.error': 'Credenciales inválidas',
    'login.errorGeneric': 'Ocurrió un error. Por favor intenta de nuevo.',
    'login.required': 'Todos los campos son obligatorios',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.noAccount': '¿No tienes una cuenta?',
    'login.signUp': 'Registrarse',

    // ===== BAG COMPONENT =====
    'bag.title': 'Bolsa de Préstamos',
    'bag.items': 'Artículos',
    'bag.empty': 'Tu bolsa está vacía',
    'bag.emptyDesc': 'Escanea herramientas para agregarlas a tu bolsa de préstamos',
    'bag.viewBag': 'Ver Bolsa',
    'bag.clearAll': 'Limpiar Todo',
    'bag.confirmLoan': 'Confirmar Préstamo',
    'bag.remove': 'Eliminar',
    'bag.itemAdded': 'Artículo agregado a la bolsa',
    'bag.itemRemoved': 'Artículo eliminado de la bolsa',
    'bag.tooltip': 'Bolsa de Préstamos',

    // ===== CART COMPONENT =====
    'cart.title': 'Carrito de Solicitudes',
    'cart.items': 'Artículos',
    'cart.empty': 'Tu carrito está vacío',
    'cart.emptyDesc': 'Escanea materiales para agregarlos a tu carrito de solicitudes',
    'cart.viewCart': 'Ver Carrito',
    'cart.clearAll': 'Limpiar Todo',
    'cart.confirmRequest': 'Confirmar Solicitud',
    'cart.remove': 'Eliminar',
    'cart.quantity': 'Cantidad',
    'cart.total': 'Total de Artículos',
    'cart.tooltip': 'Carrito de Solicitudes',

    // ===== VAULT COMPONENT =====
    'vault.title': 'Bóveda de Devoluciones',
    'vault.items': 'Artículos',
    'vault.empty': 'Tu bóveda está vacía',
    'vault.emptyDesc': 'Escanea herramientas para agregarlas a tu bóveda de devoluciones',
    'vault.viewVault': 'Ver Bóveda',
    'vault.clearAll': 'Limpiar Todo',
    'vault.confirmReturn': 'Confirmar Devolución',
    'vault.remove': 'Eliminar',
    'vault.itemAdded': 'Artículo agregado a la bóveda',
    'vault.itemRemoved': 'Artículo eliminado de la bóveda',
    'vault.tooltip': 'Bóveda de Devoluciones',

    // ===== LOAN CONFIRMATION MODAL =====
    'loanConfirmation.title': 'Confirmar Préstamo',
    'loanConfirmation.dueDate': 'Fecha de Vencimiento',
    'loanConfirmation.selectDate': 'Seleccionar fecha de vencimiento',
    'loanConfirmation.notes': 'Notas',
    'loanConfirmation.notesPlaceholder': 'Agrega notas sobre este préstamo (opcional)',
    'loanConfirmation.itemsToLoan': 'Artículos a Prestar',
    'loanConfirmation.cancel': 'Cancelar',
    'loanConfirmation.confirm': 'Confirmar Préstamo',
    'loanConfirmation.confirming': 'Confirmando...',
    'loanConfirmation.success': 'Préstamo confirmado exitosamente',
    'loanConfirmation.error': 'Error al confirmar préstamo',

    // ===== SCANNER COMPONENT =====
    'scanner.batch.title': 'Escaneo por Lotes',
    'scanner.batch.mode': 'Modo Lote',
    'scanner.batch.count': 'Escaneados: {count}',
    'scanner.batch.confirm': 'Confirmar Lote',
    'scanner.batch.clear': 'Limpiar Lote',
    'scanner.batch.empty': 'No hay artículos escaneados',
    'scanner.quantity.title': 'Ingresar Cantidad',
    'scanner.quantity.label': 'Cantidad',
    'scanner.quantity.placeholder': 'Ingresa la cantidad',
    'scanner.quantity.confirm': 'Confirmar',
    'scanner.quantity.cancel': 'Cancelar',
    'scanner.quantity.invalid': 'Por favor ingresa una cantidad válida',
    'scanner.quantity.required': 'La cantidad es obligatoria',
    'scanner.multiMode.single': 'Modo Individual',
    'scanner.multiMode.batch': 'Modo Lote',
    'scanner.multiMode.tooltip': 'Cambiar modo de escaneo',
    'scanner.error.notFound': 'Artículo no encontrado',
    'scanner.error.alreadyScanned': 'Artículo ya escaneado',
    'scanner.error.unavailable': 'Artículo no disponible',
    'scanner.error.invalidQR': 'Código QR inválido',
    'scanner.error.cameraPermission': 'Permiso de cámara denegado',
    'scanner.error.cameraNotFound': 'No se encontró cámara',

    // ===== BULK IMPORT (Extended) =====
    'bulkImport.instructions': 'Sube un archivo CSV para importar múltiples artículos a la vez',
    'bulkImport.step1': 'Descarga la plantilla',
    'bulkImport.step2': 'Completa tus datos',
    'bulkImport.step3': 'Sube el archivo completado',
    'bulkImport.validating': 'Validando...',
    'bulkImport.rowsProcessed': 'Filas procesadas: {count}',
    'bulkImport.errors': 'Errores encontrados',
    'bulkImport.errorRow': 'Fila {row}: {error}',
    'bulkImport.preview': 'Vista Previa',
    'bulkImport.previewTitle': 'Vista Previa de Importación',
    'bulkImport.previewDesc': 'Revisa los artículos antes de importar',
    'bulkImport.confirmImport': 'Confirmar Importación',
    'bulkImport.backToUpload': 'Volver a Subir',
    'bulkImport.duplicateFound': 'Artículo duplicado encontrado',
    'bulkImport.invalidFormat': 'Formato de archivo inválido',

    // ===== FORM VALIDATION =====
    'form.required': 'Este campo es obligatorio',
    'form.invalidEmail': 'Dirección de correo electrónico inválida',
    'form.invalidNumber': 'Por favor ingresa un número válido',
    'form.minLength': 'Debe tener al menos {min} caracteres',
    'form.maxLength': 'No debe tener más de {max} caracteres',
    'form.minValue': 'Debe ser al menos {min}',
    'form.maxValue': 'No debe ser más de {max}',
    'form.invalidDate': 'Fecha inválida',
    'form.pastDate': 'La fecha no puede estar en el pasado',
    'form.futureDate': 'La fecha no puede estar en el futuro',
    'form.invalidUrl': 'URL inválida',
    'form.passwordMismatch': 'Las contraseñas no coinciden',
    'form.saving': 'Guardando...',

    // ===== ELECTRONICS =====
    'electronics.title': 'Dispositivos Electrónicos',
    'electronics.addNew': 'Agregar Nuevo Dispositivo',
    'electronics.backToDashboard': 'Volver al Panel',
    'electronics.totalDevices': 'Dispositivos Totales',
    'electronics.available': 'Disponibles',
    'electronics.loaned': 'Prestados',
    'electronics.maintenance': 'Mantenimiento',
    'electronics.search': 'Buscar',
    'electronics.searchPlaceholder': 'Buscar por nombre, marca, modelo o serial...',
    'electronics.filterByStatus': 'Filtrar por Estado',
    'electronics.filterByCategory': 'Filtrar por Categoría',
    'electronics.allStatus': 'Todos los Estados',
    'electronics.allCategories': 'Todas las Categorías',
    'electronics.activeFilters': 'Filtros activos:',
    'electronics.clearAll': 'Limpiar todo',
    'electronics.noDevicesFound': 'No se Encontraron Dispositivos',
    'electronics.noDevicesMatch': 'No hay dispositivos que coincidan con tu búsqueda.',
    'electronics.noDevicesYet': 'No se han agregado dispositivos electrónicos aún.',
    'electronics.clearFilters': 'Limpiar Filtros',
    'electronics.viewDetails': 'Ver Detalles',
    'electronics.brand': 'Marca',
    'electronics.model': 'Modelo',
    'electronics.serial': 'Serial',
    'electronics.category': 'Categoría',
    'electronics.added': 'Agregado',
    'electronics.notes': 'Notas',
    'electronics.loadingDevices': 'Cargando dispositivos...',
    'electronics.deviceDetails': 'Detalles del Dispositivo',
    'electronics.specifications': 'Especificaciones',
    'electronics.conditionNotes': 'Notas de Condición',
    'electronics.currentlyLoaned': 'Actualmente Prestado',
    'electronics.editDevice': 'Editar Dispositivo',
    'electronics.deleteDevice': 'Eliminar Dispositivo',
    'electronics.deleting': 'Eliminando...',
    'electronics.confirmDelete': 'Confirmar Eliminación',
    'electronics.confirmDeleteMessage': '¿Estás seguro de que deseas eliminar este dispositivo? Esta acción no se puede deshacer.',
    'electronics.cannotDeleteWithLoan': 'No se puede eliminar un dispositivo con préstamo activo',
    'electronics.createDevice': 'Crear Dispositivo',
    'electronics.updateDevice': 'Actualizar Dispositivo',
    'electronics.creating': 'Creando...',
    'electronics.updating': 'Actualizando...',
    'electronics.deviceCreated': '¡Dispositivo creado exitosamente!',
    'electronics.deviceUpdated': '¡Dispositivo actualizado exitosamente!',
    'electronics.deviceDeleted': '¡Dispositivo eliminado exitosamente!',
    'electronics.errorCreating': 'Error al crear el dispositivo',
    'electronics.errorUpdating': 'Error al actualizar el dispositivo',
    'electronics.errorDeleting': 'Error al eliminar el dispositivo',
    'electronics.errorLoading': 'Error al cargar el dispositivo',
    'electronics.name': 'Nombre',
    'electronics.description': 'Descripción',
    'electronics.status': 'Estado',
    'electronics.conditionNotesLabel': 'Notas de Condición',
    'electronics.enterName': 'Ingresa el nombre del dispositivo',
    'electronics.enterDescription': 'Ingresa la descripción del dispositivo',
    'electronics.enterBrand': 'ej., Apple, Dell, HP',
    'electronics.enterModel': 'ej., MacBook Pro, Latitude 5420',
    'electronics.enterSerial': 'Ingresa el número de serie',
    'electronics.enterConditionNotes': 'Notas sobre la condición del dispositivo',
    'electronics.dangerZone': 'Zona de Peligro',
    'electronics.dangerZoneDesc': 'Una vez que elimines un dispositivo, no hay vuelta atrás. Por favor, asegúrate.',
    'electronics.tips': 'Consejos',
    'electronics.tip1': 'Se generará automáticamente un código QR para este dispositivo',
    'electronics.tip2': 'La información de marca y modelo ayuda con la identificación',
    'electronics.tip3': 'Los números de serie son útiles para garantía y seguimiento',
    'electronics.tip4': 'Agrega notas de condición para cualquier problema existente o características especiales',

    // Electronics Categories
    'electronics.category.laptops': 'Laptops',
    'electronics.category.tablets': 'Tablets',
    'electronics.category.smartphones': 'Smartphones',
    'electronics.category.peripherals': 'Periféricos',
    'electronics.category.digital': 'Digitales',
    'electronics.category.others': 'Otros',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  useEffect(() => {
    // Update HTML lang attribute when language changes
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string, variables?: Record<string, string | number>): string => {
    // Get translation from current language
    let translation = translations[language][key as keyof typeof translations.en]

    // Fallback to English if translation not found in current language
    if (!translation && language !== 'en') {
      translation = translations['en'][key as keyof typeof translations.en]
      if (translation) {
        console.warn(`Translation missing for key: ${key} in ${language}, using English fallback`)
      }
    }

    // If still no translation found, show key in brackets for debugging
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in all languages`)
      return `${key}`
    }

    // Handle variable interpolation
    if (variables) {
      return Object.entries(variables).reduce(
        (text, [varName, value]) => text.replace(new RegExp(`\\{${varName}\\}`, 'g'), String(value)),
        translation
      )
    }

    return translation
  }

  const formatDate = (date: Date | string, format: 'short' | 'long' | 'relative' = 'short'): string => {
    const dateObj = typeof date === 'string' ? new Date(date) : date

    if (isNaN(dateObj.getTime())) {
      return 'Invalid Date'
    }

    const locale = language === 'es' ? 'es-ES' : 'en-US'

    if (format === 'relative') {
      const now = new Date()
      const diffInSeconds = Math.floor((now.getTime() - dateObj.getTime()) / 1000)

      if (diffInSeconds < 60) {
        return language === 'es' ? 'Justo ahora' : 'Just now'
      } else if (diffInSeconds < 3600) {
        const minutes = Math.floor(diffInSeconds / 60)
        return language === 'es'
          ? `Hace ${minutes} minuto${minutes !== 1 ? 's' : ''}`
          : `${minutes} minute${minutes !== 1 ? 's' : ''} ago`
      } else if (diffInSeconds < 86400) {
        const hours = Math.floor(diffInSeconds / 3600)
        return language === 'es'
          ? `Hace ${hours} hora${hours !== 1 ? 's' : ''}`
          : `${hours} hour${hours !== 1 ? 's' : ''} ago`
      } else if (diffInSeconds < 2592000) {
        const days = Math.floor(diffInSeconds / 86400)
        return language === 'es'
          ? `Hace ${days} día${days !== 1 ? 's' : ''}`
          : `${days} day${days !== 1 ? 's' : ''} ago`
      } else if (diffInSeconds < 31536000) {
        const months = Math.floor(diffInSeconds / 2592000)
        return language === 'es'
          ? `Hace ${months} mes${months !== 1 ? 'es' : ''}`
          : `${months} month${months !== 1 ? 's' : ''} ago`
      } else {
        const years = Math.floor(diffInSeconds / 31536000)
        return language === 'es'
          ? `Hace ${years} año${years !== 1 ? 's' : ''}`
          : `${years} year${years !== 1 ? 's' : ''} ago`
      }
    } else if (format === 'long') {
      return dateObj.toLocaleDateString(locale, {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })
    } else {
      // short format
      return dateObj.toLocaleDateString(locale, {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit'
      })
    }
  }

  const formatNumber = (num: number): string => {
    const locale = language === 'es' ? 'es-ES' : 'en-US'
    return num.toLocaleString(locale)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatDate, formatNumber }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
