import { NextRequest, NextResponse } from 'next/server'
import { toolInstanceOperations, auditLogOperations } from '@/lib/supabase-client'
import { withPermission } from '@/lib/auth-middleware'
import { PERMISSIONS } from '@/lib/permissions'
import { createToolInstanceSchema } from '@/utils/validation'
import { ERROR_CODES, ERROR_MESSAGES } from '@/utils/constants'
import type { ToolFilters, ToolInstance } from '@/types/database'

export async function GET(request: NextRequest) {
  try {
    return await withPermission(request, PERMISSIONS.ADMIN_MANAGE_TOOLS, async (authContext) => {
      const { searchParams } = new URL(request.url)
      
      // Build filters from query parameters
      const filters: ToolFilters = {}
      
      const status = searchParams.get('status')
      if (status) {
        filters.status = status as ToolInstance['status']
      }
      
      const category = searchParams.get('category')
      if (category) {
        filters.category = category
      }
      
      const itemTypeId = searchParams.get('item_type_id')
      if (itemTypeId) {
        const parsed = parseInt(itemTypeId, 10)
        if (!isNaN(parsed)) {
          filters.item_type_id = parsed
        }
      }

      // Get tools with filters (admins see all tools)
      const tools = await toolInstanceOperations.getAll(filters)

      // Add summary statistics
      const statusSummary = tools.reduce((acc, tool) => {
        acc[tool.status] = (acc[tool.status] || 0) + 1
        return acc
      }, {} as Record<string, number>)

      return NextResponse.json({
        data: tools,
        total: tools.length,
        filters: filters,
        summary: {
          by_status: statusSummary,
          total_tools: tools.length,
        },
      })
    })
  } catch (error: unknown) {
    console.error('Admin tools fetch error:', error)

    if (error instanceof Error && error.name === 'AuthenticationError') {
      return NextResponse.json(
        {
          error: {
            code: ERROR_CODES.AUTHENTICATION_ERROR,
            message: error.message,
            timestamp: new Date().toISOString(),
          },
        },
        { status: 401 }
      )
    }

    if (error instanceof Error && error.name === 'AuthorizationError') {
      return NextResponse.json(
        {
          error: {
            code: ERROR_CODES.AUTHORIZATION_ERROR,
            message: error.message,
            timestamp: new Date().toISOString(),
          },
        },
        { status: 403 }
      )
    }

    return NextResponse.json(
      {
        error: {
          code: ERROR_CODES.DATABASE_ERROR,
          message: ERROR_MESSAGES.GENERIC_ERROR,
          timestamp: new Date().toISOString(),
        },
      },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    return await withPermission(request, PERMISSIONS.ADMIN_MANAGE_TOOLS, async (authContext) => {
      const body = await request.json()
      
      // Validate input
      const validatedData = createToolInstanceSchema.validateSync(body)

      // Create the tool instance (UUID will be auto-generated if not provided)
      const tool = await toolInstanceOperations.create({
        ...validatedData,
        qr_code: validatedData.qr_code || '', // Will be generated by the operation if empty
      })

      // Create audit log
      try {
        await auditLogOperations.create({
          user_id: authContext.user.id,
          action: 'tool_create',
          entity_type: 'tool_instance',
          entity_id: tool.id,
          new_values: {
            ...validatedData,
            qr_code: tool.qr_code, // Include the generated QR code
          },
          ip_address: request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || 'unknown',
          user_agent: request.headers.get('user-agent') || 'unknown',
        })
      } catch (auditError) {
        console.error('Failed to create audit log:', auditError)
      }

      return NextResponse.json({
        data: tool,
        message: 'Tool created successfully',
      }, { status: 201 })
    })
  } catch (error: unknown) {
    console.error('Tool creation error:', error)

    if (error instanceof Error && error.name === 'ValidationError') {
      return NextResponse.json(
        {
          error: {
            code: ERROR_CODES.VALIDATION_ERROR,
            message: error.message,
            timestamp: new Date().toISOString(),
          },
        },
        { status: 400 }
      )
    }

    if (error instanceof Error && error.name === 'AuthenticationError') {
      return NextResponse.json(
        {
          error: {
            code: ERROR_CODES.AUTHENTICATION_ERROR,
            message: error.message,
            timestamp: new Date().toISOString(),
          },
        },
        { status: 401 }
      )
    }

    if (error instanceof Error && error.name === 'AuthorizationError') {
      return NextResponse.json(
        {
          error: {
            code: ERROR_CODES.AUTHORIZATION_ERROR,
            message: error.message,
            timestamp: new Date().toISOString(),
          },
        },
        { status: 403 }
      )
    }

    return NextResponse.json(
      {
        error: {
          code: ERROR_CODES.DATABASE_ERROR,
          message: ERROR_MESSAGES.GENERIC_ERROR,
          timestamp: new Date().toISOString(),
        },
      },
      { status: 500 }
    )
  }
}